import "./globals.css";

import { Inter } from "next/font/google";
import StyledLayout from "./styled.layout";
import { Suspense } from "react";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <Suspense fallback="Loading...">
          <StyledLayout>{children}</StyledLayout>
        </Suspense>
      </body>
    </html>
  );
}
